### ISSUE TITLE
Not working with later version of React Native (0.47+)

### ISSUE THREAD

**Issue by hanssonfredrik** [veeloinc/react-native-mime-intent#4]
A major change in react native makes the java part break. Remove the @Override on all functions in the MainIntentPackage.java to fix it.

**Comment by daqiuqu** [comment]
[pr2](https://github.com/veeloinc/react-native-mime-intent/pull/2) not working?

**Comment by hanssonfredrik** [comment]
@daqiuqu yes it worked! Had to fork it though.
